name: Terraform ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'infra'
    steps:
      - uses: actions/checkout@v2 # Checks out git repository
      - uses: hashicorp/setup-terraform@v1 # Some handy function for terraform? https://github.com/hashicorp/setup-terraform
      - name: Terraform init
        run: terraform init
      - name: Terraform validate
        run: terraform validate
      - name: Terraform plan
        if: github.event_name == 'pull_request'
        run: terraform plan
      - name: Terraform apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approves